service: ingredients-api

provider:
  name: aws
  runtime: nodejs10.x # set node.js runtime
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: ap-southeast-1

functions:
  server:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

package:
  exclude:
    - venv/**
    - serverless/**
    - images/**
    - database/**
